//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by avlib.rc
//
#define IDOK                            1
#define IDCANCEL                        2
#define IDD_FF_INFO                     102
#define IDD_FFLAYER                     103
#define IDD_ENC_FFV1                    104
#define IDB_FFMPEG                      105
#define IDD_ENC_FFVHUFF                 105
#define IDD_EXPORT_PROGRESS             106
#define IDD_SYS_INPUT_OPTIONS           107
#define IDD_ENC_PRORES                  108
#define IDD_ENC_MP3                     109
#define IDD_ENC_AAC                     110
#define IDD_ENC_VP8                     111
#define IDD_INPUT_OPTIONS               112
#define IDB_CINEFORM                    112
#define IDD_ENC_X265                    113
#define IDD_ENC_CINEFORM                114
#define IDD_ENC_X265LS                  115
#define IDD_ENC_VP9                     116
#define IDD_ENC_FLAC                    117
#define IDD_ENC_OPUS                    118
#define IDD_ENC_ALAC                    119
#define IDD_ENC_VORBIS                  120
#define IDD_FFLAYER_FILE                121
#define IDC_FORMATNAME                  1004
#define IDC_VIDEO_PIXFMT                1006
#define IDC_VIDEO_WXH                   1007
#define IDC_VIDEO_BITRATE               1008
#define IDC_VIDEO_FRAMERATE             1009
#define IDC_IFHEIGHT720_710             1009
#define IDC_VIDEO_ASPECTRATIO           1010
#define IDC_VIDEO_CODECNAME             1011
#define IDC_AUDIO_CODECNAME             1012
#define IDC_AUDIO_CHANNELS              1013
#define IDC_AUDIO_SAMPLEFMT             1014
#define IDC_AUDIO_LAYOUT                1015
#define IDC_AUDIO_SAMPLERATE            1016
#define IDC_DURATION                    1017
#define IDC_STARTTIME                   1018
#define IDC_STREAMSCOUNT                1019
#define IDC_BITRATE                     1020
#define IDC_AUDIO_BITRATE               1021
#define IDC_COMBO1                      1022
#define IDC_VIDEO_CODECNAME2            1022
#define IDC_METADATA                    1022
#define IDC_COLORSPACE                  1022
#define IDC_STATICVerNumber             1023
#define IDC_COMBODEFAULTVIDEO2          1023
#define IDC_PREDICTION                  1023
#define IDC_LEVEL                       1023
#define IDC_SLICES                      1024
#define IDC_INDEX_INFO                  1025
#define IDC_MEMORY_INFO                 1026
#define IDC_SEGMENT                     1027
#define IDC_SEGMENT_PREV                1028
#define IDC_SEGMENT_NEXT                1029
#define IDC_LOGOFILE                    1029
#define IDC_SEGMENT2                    1030
#define IDC_SEGMENT_TIMELINE            1030
#define IDC_LOGOFILE_BROWSE             1031
#define IDC_STATS                       1031
#define IDC_ALPHABLEND                  1032
#define IDC_PREMULTALPHA                1033
#define IDC_PREVIEW                     1034
#define IDPREVIEW                       1034
#define IDC_XPOS                        1035
#define IDC_CHECK5                      1036
#define IDC_YPOS                        1036
#define IDC_FILE_INFO                   1037
#define IDC_ANIM_SINGLE                 1038
#define IDC_ANIM_FOLLOW                 1039
#define IDC_ENCODER_LABEL               1039
#define IDC_REF_SINGLE                  1040
#define IDC_8_BIT                       1040
#define IDC_REF_FOLLOW                  1041
#define IDC_9_BIT                       1041
#define IDC_EXPORT_PROGRESS             1041
#define IDC_ENCODER_LABEL2              1041
#define IDC_LOOP                        1042
#define IDC_10_BIT                      1042
#define IDC_EXPORT_STATE                1042
#define IDC_REF_FOLLOW2                 1043
#define IDC_FOLLOW_RATE                 1043
#define IDC_12_BIT                      1043
#define IDC_DECODE_RAW                  1043
#define IDC_14_BIT                      1044
#define IDC_DECODE_MAGIC                1044
#define IDC_16_BIT                      1045
#define IDC_DECODE_CFHD                 1045
#define IDC_PROFILE                     1046
#define IDC_FORCE_THREAD                1046
#define IDC_DISABLE_CACHE               1046
#define IDC_QUALITY                     1047
#define IDC_FORCE_THREAD2               1047
#define IDC_DISABLE_CACHE2              1047
#define IDC_DECODE_CFHD_AM              1047
#define IDC_QUALITY_VALUE               1048
#define IDC_STEREO                      1049
#define IDC_TUNE                        1049
#define IDC_CBR                         1050
#define IDC_QUALITY_LABEL               1051
#define IDC_CODER0                      1052
#define IDC_CODER1                      1053
#define IDC_CONTEXT                     1054
#define IDC_SLICECRC                    1055
#define IDC_MESSAGE                     1056
#define IDC_SYS_OPTIONS                 1057
#define IDC_DECODE_FFMPEG               1058
#define IDC_CACHE_SIZE                  1059
#define IDC_SPIN1                       1060
#define IDC_CACHE_SPIN                  1060
#define IDC_THREADING                   1061
#define IDC_LINK                        1062
#define IDC_ABR                         1063
#define IDC_BITRATE_VALUE               1064
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
